<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ParcelPilot.Application\ParcelPilot.Application.csproj" />
    <ProjectReference Include="..\ParcelPilot.Domain\ParcelPilot.Domain.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
</Project>
